config-version: '${config_version}'

# file:
#   JSON
#   YAML
#
# local database
#   SQLite
#   H2 (preferred over SQLite)
#
# remote database
#   MySQL
#   MariaDB (preferred over MySQL)
#   MongoDB
#
data-storage-method: H2

SQLite:
  file: 'sqlite'
  table-prefix: customfishing

H2:
  file: 'h2'
  table-prefix: customfishing

MySQL:
  host: 'localhost'
  port: '3306'
  user: 'root'
  password: 'password'
  database: 'minecraft'
  connection-parameters: '?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8'
  Pool-Settings:
    max-pool-size: 10
    min-idle: 10
    max-lifetime: 180000
    keep-alive-time: 60000
    time-out: 20000
  table-prefix: customfishing

MariaDB:
  host: 'localhost'
  port: '3306'
  user: 'root'
  password: 'password'
  database: 'minecraft'
  connection-parameters: '?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8'
  Pool-Settings:
    max-pool-size: 10
    min-idle: 10
    max-lifetime: 180000
    keep-alive-time: 60000
    time-out: 20000
  table-prefix: customfishing

MongoDB:
  host: 'localhost'
  port: '27017'
  user: ''
  password: ''
  # If this section is not empty, it would override the configs above
  # https://www.mongodb.com/docs/manual/reference/connection-string/
  connection-uri: ''
  database: 'minecraft'
  collection-prefix: customfishing

# Redis is optional if you are using remote database
# If you do not know how to use Redis, please do not enable it
Redis:
  enable: false
  host: localhost
  password: ""
  port: 6379
  use-ssl: false
  MaxTotal: 10
  MaxIdle: 10
  MinIdle: 1
  MaxWaitMillis: 30000
  MinEvictableIdleTimeMillis: 1800000