name: Build Development

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Extract repository name
        run: echo "NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Upload Build
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "${{ env.NAME }}"
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "target/*.jar"
          prerelease: false
